### ISSUE TITLE
Some strange issue which can be possible linked with rewire module

### ISSUE THREAD

**Issue by tormozz48** [jhnns/rewire#64]
I have stack trace:

```
SyntaxError: Unexpected token -
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Object.load (/Users/bemer/Work/builder-docs/node_modules/mock-fs/node_modules/rewire/lib/moduleEnv.js:19:18)
    at internalRewire (/Users/bemer/Work/builder-docs/node_modules/mock-fs/node_modules/rewire/lib/rewire.js:56:15)
    at rewire (/Users/bemer/Work/builder-docs/node_modules/mock-fs/node_modules/rewire/lib/index.js:11:12)
    at Object.<anonymous> (/Users/bemer/Work/builder-docs/node_modules/mock-fs/lib/index.js:41:14)
```  

Can some last changes in rewire module cause this error?

**Comment by essekia** [comment]
I have the same issue. Can you tell me how you resolved this?
